version: 2

sources:
  - name: weather_tables
    database: weather-project-498116  # ID của Google Cloud Project
    schema: weather_info           # Tên Dataset trong BigQuery
    tables:
      - name: weather_final         # Tên bảng thô đã đẩy lên